### ISSUE TITLE
Shortcode Properties Not Working

### ISSUE THREAD

**Issue by db123v** [michielvaneerd/privategooglecalendars#1]
Hi, I was using the following shortcode properties, however the display of the calendar on my website remained to Month view by default with all header properties visible. The only property that seemed to have work was the filter ="false"

[pgc
header-left=""
header-right=""
header-center=""
default_view="listWeek"
filter="false"]

Your assistance with this would be higly appreciated.

Thanks

**Comment by michielvaneerd** [comment]
I tried the same shortcode and for me it's working as you can see on https://blog.michielvaneerd.nl/calendar-test/. Are you using the latest version of the plugin (20191211)? And to be sure: do you enter the shortcode on one line (and not multiline as above)?

**Comment by db123v** [comment]
Thanks a lot for the feedback. I indeed had the shortcode on multiple lines and that was why it wasnt displaying. It is working fine now as per your instructions. Once again thank you very much for your assistance.
