### ISSUE TITLE
Update the Setup Instructions?

### ISSUE THREAD

**Issue by alexmustin** [michielvaneerd/privategooglecalendars#17]
First I'd like to say thanks @michielvaneerd  for making this plugin!

Is there any way the [Setup Instructions site](https://michielvaneerd.github.io/privategooglecalendars/#installation-and-configuration) can be updated for how Google works now (as of May 2021) ?

The very first segment of instructions is outdated, and now it seems much more complicated and confusing to setup the required OAuth Key on Google Cloud. 

Any steps you can provide on this new Google Cloud setup would be helpful.

Thanks in advance!

**Comment by michielvaneerd** [comment]
This has been updated.
