### ISSUE TITLE
Update colorlist button missing from Settings

### ISSUE THREAD

**Issue by degive** [michielvaneerd/privategooglecalendars#29]
The documentation says to "Update colorlist button in the settings page", but there is no such button in the settings?

>>If you specify custom colors for events, this plugin will display them but first you have to download the Google colors. This can be done by clicking the Update colorlist button in the settings page.<
![pgc2](https://user-images.githubusercontent.com/25804247/145624117-cf59e515-719a-4a5a-a4ac-3ff05f176f2c.jpg)
![pgc1](https://user-images.githubusercontent.com/25804247/145624120-e6e7b1a9-7377-4d40-8480-beed604e67ab.jpg)
<

**Comment by michielvaneerd** [comment]
It's beneath the "Tools" section at the bottom of this page.

**Comment by degive** [comment]
Sorry I still cannot find it

**Comment by degive** [comment]
I found it finally. I had not created a project in google, was just using api key, now this works.
