### ISSUE TITLE
No selected Calendars issue

### ISSUE THREAD

**Issue by thomasthesbjerg** [michielvaneerd/privategooglecalendars#3]
I keep getting this message in console:
![image](https://user-images.githubusercontent.com/1616692/74105349-4d59e480-4b5d-11ea-9742-a4f2590f35d3.png)

The Id's are verified and set in Plugin settings:
![image](https://user-images.githubusercontent.com/1616692/74105392-93af4380-4b5d-11ea-828a-50457cc8105f.png)

Shortcode is taken from your guide:
![image](https://user-images.githubusercontent.com/1616692/74105404-af1a4e80-4b5d-11ea-85e5-edbd86caba48.png)

(Calender is public)

**Comment by michielvaneerd** [comment]
Hi,

In the shortcode, you have to specify only the calendar ID, for example "nl.christian#holiday@group.v.calendar.google.com". You can see the calendar ID in the settings page of the Google calendar.

If it is a public calendar, you also need to add public="true" to the shortcode. I see that this is not in the documentation, so I will add this. Thanks for letting me know!

Example:

`[pgc public="true" calendarids="nl.christian#holiday@group.v.calendar.google.com"]`

**Comment by thomasthesbjerg** [comment]
Thank you for your Quick reply, that helped a lot.
