### ISSUE TITLE
Background & Foreground Colors

### ISSUE THREAD

**Issue by degive** [michielvaneerd/privategooglecalendars#30]
I would like to be able to set both background and foreground colors for a calendar, not just background the way you have it now. I want it to look more like the google calendar. I have attached google screenshot and PGC screenshot so you can see the differences.

Also would like to be able to highlight day event like google does. Maybe reverse the color for day events?

![pgc](https://user-images.githubusercontent.com/25804247/145723682-ed78471a-fdfb-4532-a3eb-2053e967999c.jpg)
![google](https://user-images.githubusercontent.com/25804247/145723684-c2b4704e-c147-4adc-af1c-53f943e6ab39.jpg)

Thank you. Great Plugin!

**Comment by degive** [comment]
Hello, I haven't heard back from you on this. Any chance we can get that fixed? Thank you!

**Comment by michielvaneerd** [comment]
This is not possible without adding your own CSS because this plugin uses FullCalendar and FullCalendar always gives whoe day events a background color and other events a coloured circle.
