### ISSUE TITLE
PHP8.0 has deprecated the use of optional parameters before required parameters.

### ISSUE THREAD

**Issue by aloMalbarez** [michielvaneerd/privategooglecalendars#40]
> PHP Deprecated:  Required parameter $tag follows optional parameter $atts in [...]/wp-content/plugins/private-google-calendars/private-google-calendars.php on line 204

https://github.com/michielvaneerd/privategooglecalendars/blob/b402081e4a73189bbc4f43fb8ad928d2e1d32cef/private-google-calendars.php#L204

I guess `$tag = null` should be enough

**Comment by michielvaneerd** [comment]
Hi thanks for reporting. I've fixed this in this GitHub repository and will update the plugin in the next coming days.
