### ISSUE TITLE
Day text is not seperated and scrolling is ugly

### ISSUE THREAD

**Issue by theincogtion** [michielvaneerd/privategooglecalendars#48]
While scrolling through a list the day title is mixed up with the text of the calender.
![grafik](https://user-images.githubusercontent.com/10852327/201095065-ef9becca-36d1-46e9-8b16-489dd159d974.png)
Especially ugly on mobile devices.

Can also be observed here:
https://blog.michielvaneerd.nl/wordpress-plugins/private-google-calendars/
While watching on mobile.

Feel free to change the title of this request.

**Comment by michielvaneerd** [comment]
Hi I cannot reproduce this, also not on the URL you provides - see below:

![Screenshot 2023-01-07 at 13 33 00](https://user-images.githubusercontent.com/375532/211150832-fbb46a0b-d991-4d7a-b10a-5af5efdf750f.png)

**Comment by theincogtion** [comment]
You have to scroll the list to see the problem.
I can reproduce it on Firefox Mobile and Firefox Desktop:
![grafik](https://user-images.githubusercontent.com/10852327/211152196-291a9163-9b02-4f16-80d3-ce82a7c5bf9a.png)
On chrome it seems to work fine:
![grafik](https://user-images.githubusercontent.com/10852327/211152232-63cb1971-e866-4bc1-8b13-df2d9e5642ce.png)

**Comment by michielvaneerd** [comment]
Okay, this is a FullCalendar bug. This plugin uses FullCalendar to display the calendar. Maybe you can fill a bug report over there?

**Comment by theincogtion** [comment]
2 years old:
https://github.com/fullcalendar/fullcalendar/issues/6230
https://github.com/fullcalendar/fullcalendar/issues/6896

**Comment by michielvaneerd** [comment]
Ah thanks, so this can be solved by setting the `stickyHeaderDates` property in the Gutenberg config, for example:

```
{
  "headerToolbar": {
    "start": "prev,next today",
    "center": "title",
    "end": "dayGridMonth,timeGridWeek,listWeek"
  },
  "stickyHeaderDates": false
}
```

Or when using the shortcode:

`[pgc sticky_header_dates="false"]`
