### ISSUE TITLE
Popup always shows en-en locale

### ISSUE THREAD

**Issue by telepibe** [michielvaneerd/privategooglecalendars#50]
Hello and happy new year.

### Issue
Tippy popup shows wrong translation even when the calendar itself is showing in the locale of WordPress site.

#### More info:
Developers tools show that `pgc_object.trans` has
```
​all_day: "All day"​
created_by: "Created by"​
go_to_event: "Go to event"​
loading: "Loading"
request_error: "Request error"
unknown_error: "Unknown error"
```
Even when forcing locale through fullcalendar config or shortcode attribute has no change in popup translation.

Thanks for this awesome plugin.

**Comment by michielvaneerd** [comment]
Hi, these texts have only been translated to Dutch (mu language) and Czech (a user provided this to me). So that's the reason why you don't see your translation. You can provide the translation at https://translate.wordpress.org/projects/wp-plugins/private-google-calendars/.
