### ISSUE TITLE
Calendars not rendering / javascript error in version 20240103

### ISSUE THREAD

**Issue by wykananda** [michielvaneerd/privategooglecalendars#55]
Calendars are not rendering for me in version  20240103 - just an empty placeholder.  The _data-config_ html attribute appears to be being assigned _"null"_ and causing the function listed below to fail.  This happens even if I replace my custom config with the default in the Gutenberg block.

Here's one of the pages where the failure is occurring -> [Calendar](https://katog.org/kr-calendar/)

Here's the HTML that's being generated for the calendar:
`<div data-calendarids="[&quot;mywebsite.com_f7tv84tnvqojte8vnv778gc9qo@group.calendar.google.com&quot;]" data-filter="" data-eventpopup="true" data-eventlink="true" data-eventdescription="true" data-eventlocation="true" data-eventattachments="true" data-eventattendees="false" data-eventcreator="false" data-eventcalendarname="false" data-hidefuture="false" data-hidepassed="false" data-config="null" data-locale="en_US" data-theme="pgc-light" class="pgc-calendar"></div>`

Here's the error appearing in the browser console - Function castObjectAttributes(obj) is being fed a null config:

main.js:73 Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at i (main.js:73:16)
    at main.js:166:9
    at NodeList.forEach (<anonymous>)
    at HTMLDocument.<anonymous> (main.js:103:29)

Please let me know if I can provide you with any other info to help fix it.

Kind regards,
  Wyk

**Comment by wykananda** [comment]
...here's my custom config copied from the block's config text area. It worked fine in the last version of the plugin but I can't seem to make any of it work in the latest version:
`{
  "headerToolbar": {
    "start": "today prev,next",
    "center": "title",
    "end": "dayGridMonth,timeGridWeek,listWeek"
  },
  "dayMaxEvents": true,
  "aspectRatio": 1,
  "height": "auto"
}`

**Comment by wykananda** [comment]
The problem seems to be caused by the addition of the new security fix:
```
// Prevent cross site scripting
 $value = esc_attr($value);
```
See [here](https://wordpress.stackexchange.com/questions/162918/esc-attr-corrupts-json-values) for the issue and a potential solution. A more stealthy approach might be to include and use [this](https://github.com/OWASP/json-sanitizer).

**Comment by michielvaneerd** [comment]
Thank you for your detailed response. You are right that esc_attr was causing issues, and this should now be fixed. When I have more time later on, I will see if I can use esc_js but I'm not sure now. Unfortunately you will have to save the pages with calendars again to see the result of this fix.

**Comment by wykananda** [comment]
Thanks Michiel for the quick fix.  I gave a quick try using esc_js - unfortunately, it seemed to suffer from the same issue.   
I'm not sure I understand where the cross site scripting danger lies.  Is there something that could be compromised in full calendar via submitting a malformed json config? Or does the problem happen somewhere else?

Anyhow, thanks for your wonderful plugin. It's really helpful for us!
